FROM golang:latest AS builder
COPY . /app
WORKDIR /app/backend/grpc
RUN go build -o grpc_backend


FROM golang:latest
WORKDIR /app
COPY --from=builder /app/backend/grpc/grpc_backend .
EXPOSE 4000
CMD ["./grpc_backend"]